/**
 * Stores the names for each individual image within the master Atlas (omitting sequences; See SequenceNames class)
 */
var ImageNames	= {
	CHAINGUN : "chaingun.png",
	CHAINGUN_IMPACT : "chaingun_impact.png",
	CHAINGUN_MASK : "chaingun_mask.png",
	CONTAINER_CLOSED : "container_a_closed.png",
	CONTAINER_EMPTY : "container_a_empty.png",
	CONTAINER_FULL : "container_a_full.png",
	DEFENSIVE_SHIELD : "defensive_shield.png",
	DEFENSIVE_SHIELD_MASK : "defensive_shield_mask.png",
	GRENADE_LAUNCHER : "grenade_launcher.png",
	GRENADE_IMPACT : "grenade_launcher_impact.png",
	GRENADE_LAUNCHER_MASK : "grenade_launcher_mask.png",
	LANDMINE : "landmine.png",
	LANDMINE_IMPACT_LARGE : "landmine_impact_large.png",
	LANDMINE_IMPACT_SMALL : "landmine_impact_small.png",
	LANDMINE_MASK : "landmine_mask.png",
	LEGS : "legs.png",
	LEGS_PLAYER_COLOR : "legs_player_color.png",
	MACHGUN : "machinegun.png",
	MACHGUN_IMPACT : "machinegun_impact.png",
	MACHGUN_MASK : "machinegun_mask.png",
	OFFENSIVE_SHIELD : "offensive_shield.png",
	OFFENSIVE_SHIELD_MASK : "offensive_shield_mask.png",
	RAILGUN : "railgun.png",
	RAILGUN_IMPACT_GROUND : "railgun_impact_ground.png",
	RAILGUN_MASK : "railgun_mask.png",
	ROCKET_LAUNCHER : "rocket_launcher.png",
	ROCKET_IMPACT : "rocket_launcher_impact.png",
	ROCKET_LAUNCHER_MASK : "rocket_launcher_mask.png",
	SHIELD_DEFENSIVE : "shield_defensive.png",
	SHIELD_OFFENSIVE : "shield_offensive.png",
	SHOTGUN : "shotgun.png",
	SHOTGUN_IMPACT : "shotgun_impact.png",
	SHOTGUN_MASK : "shotgun_mask.png",
	THRUSTER : "thruster.png",
	THRUSTER_MASK : "thruster_mask.png",
	TURRET : "turret.png",
	TURRET_PLAYER_COLOR : "turret_player_color.png"
};