/**
 * List of names for individual sequences within the master atlas (note that only the name of the first image in the sequence is listed)
 */
var SequenceNames	= {
	CHAINGUN_IMPACT : "chaingun_impact_0000.png",
	CHAINGUN_MUZZLE : "chaingun_muzzle_0000.png",
	CHAINGUN_PROJECTILE : "chaingun_projectile_0000.png",
	CONTAINER_OPEN : "container_a_open_0000.png",
	ENERGY_BLUE : "energy_canister_blue_0000.png",
	ENERGY_RED : "energy_canister_red_0000.png",
	GRENADE_IMPACT : "grenade_launcher_impact_0000.png",
	GRENADE_MUZZLE : "grenade_launcher_muzzle_0000.png",
	GRENADE_PROJECTILE : "grenade_launcher_projectile_0000.png",
	HEALTH_BLUE : "health_canister_blue_0000.png",
	HEALTH_RED : "health_canister_red_0000.png",
	LANDMINE_EXPLOSION_LARGE : "landmine_explosion_large_0000.png",
	LANDMINE_EXPLOSION_SMALL : "landmine_explosion_small_0000.png",
	LANDMINE_IDLE : "landmine_idle_0000.png",
	MACHGUN_IMPACT : "machinegun_impact_0000.png",
	MACHGUN_MUZZLE : "machinegun_muzzle_0000.png",
	MACHGUN_PROJECTILE : "machinegun_projectile_0000.png",
	QUAD_EFFECT : "quad_effect_0000.png",
	RAILGUN_IMPACT : "railgun_impact_0000.png",
	RAILGUN_MUZZLE : "railgun_muzzle_0000.png",
	RAILGUN_PROJECTILE : "railgun_projectile_0000.png",
	ROCKET_IMPACT : "rocket_launcher_impact_0000.png",
	ROCKET_MUZZLE : "rocket_launcher_muzzle_0000.png",
	ROCKET_PROJECTILE : "rocket_launcher_projectile_0000.png",
	SHOTGUN_IMPACT : "shotgun_impact_0000.png",
	SHOTGUN_MUZZLE : "shotgun_muzzle_0000.png",
	SHOTGUN_PROJECTILE : "shotgun_projectile_0000.png",
	SPAWNER_BLACK_ACTIVATE : "spawner_black_activate_0000.png",
	SPAWNER_WHITE_ACTIVATE : "spawner_white_activate_0000.png",
	TELEPORTER_ACTIVATE : "teleporter_activate_0000.png",
	TELEPORTER_IDLE : "teleporter_idle_0000.png",
	WALK_DOWN : "walk_down_0000.png",
	WALK_DOWN_MASK : "walk_down_mask_0000.png",
	WALK_LEFT : "walk_left_0000.png",
	WALK_LEFT_MASK : "walk_left_mask_0000.png",
	WALK_RIGHT : "walk_right_0000.png",
	WALK_RIGHT_MASK : "walk_right_mask_0000.png",
	WALK_UP : "walk_up_0000.png",
	WALK_UP_MASK : "walk_up_mask_0000.png"
};